CREATE TABLE tl_wbcs_def.tb_issubclaims_hist (
  source_app_code string,
  dml_ind string,
  record_created_date timestamp,
  record_updated_date timestamp,
  record_created_by string,
  record_updated_by string,
  record_eff_from_date timestamp,
  record_eff_to_date timestamp,
  active_record_ind string,
  uuid string,
  business_key string,
  claimno string,
  policyno string,
  policyid int,
  policyshield_uuid string,
  riderid int,
  policyshieldrider_uuid string,
  peffdate timestamp,
  pexpdate timestamp,
  pooltype int,
  pooldate timestamp,
  groupentityid int,
  groupname string,
  flag string,
  flagdate timestamp,
  datecreated timestamp,
  submitterid string,
  status int,
  statusdate timestamp,
  dateclosed timestamp,
  approver string,
  approveddate timestamp,
  rejofficer string,
  rejdate timestamp,
  officer string,
  subdate string,
  gstrate decimal(18, 2),
  lastmodified timestamp,
  modifiedby string,
  printdv string,
  printdate timestamp,
  suppress string,
  pendingreqreason string,
  payableriderplan string)
PARTITIONED BY (`active_record_ind`, bucket(16, `business_key`))
LOCATION 's3://datalake-tds-dev-income-com-sg/tl_wbcs_def/tb_issubclaims_hist'
TBLPROPERTIES (
  'table_type'='iceberg',
  'optimize_rewrite_max_data_file_size_bytes'='262144001',
  'format'='parquet',
  'write_target_data_file_size_bytes'='145635556'
);